Repository nimblehq/jetpack-compose-crypto, pull requests merged in 2022-10, with the labels that each got.

#49 [#42] Setup nav graph and navigation logic
  app/build.gradle.kts
  app/src/debug/AndroidManifest.xml
  app/src/debug/java/co/nimblehq/compose/crypto/EmptyHiltActivity.kt
  app/src/main/java/co/nimblehq/compose/crypto/extension/ViewModelExt.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/BaseActivity.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/BaseComposeFragment.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/BaseComposeFragmentCallbacks.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/BaseNavigator.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/BaseViewModel.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/NavigationEvent.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/NavigationException.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/navigation/AppDestination.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/navigation/AppNavigation.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/MainActivity.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeViewModel.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/navigation/CryptoNavGraph.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/navigation/CryptoScreen.kt
  app/src/test/java/co/nimblehq/compose/crypto/ui/screens/home/HomeViewModelTest.kt
  app/src/test/resources/robolectric.properties
  build.gradle.kts
  buildSrc/src/main/java/Versions.kt
Labels: type : feature

#54 Release - 0.4.0
  app/build.gradle.kts
  app/src/debug/AndroidManifest.xml
  app/src/debug/java/co/nimblehq/compose/crypto/EmptyHiltActivity.kt
  app/src/main/java/co/nimblehq/compose/crypto/extension/ViewModelExt.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/BaseActivity.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/BaseComposeFragment.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/BaseComposeFragmentCallbacks.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/BaseNavigator.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/BaseViewModel.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/NavigationEvent.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/NavigationException.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/common/price/PriceChangeButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/navigation/AppDestination.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/navigation/AppNavigation.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/preview/DetailScreenPreviewParameterProvider.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/MainActivity.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/Appbar.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailViewModel.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/CoinItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeViewModel.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/PortfolioCard.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/TrendingItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/navigation/CryptoNavGraph.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/navigation/CryptoScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/uimodel/CoinDetailUiModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/co/nimblehq/compose/crypto/test/MockUtil.kt
  app/src/test/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailViewModelTest.kt
  app/src/test/java/co/nimblehq/compose/crypto/ui/screens/home/HomeViewModelTest.kt
  app/src/test/resources/robolectric.properties
  build.gradle.kts
  buildSrc/src/main/java/Versions.kt
Labels: type : release

#44 [#18] [UI] As a user, I can see the chart of coin prices
  app/build.gradle.kts
  app/src/main/java/co/nimblehq/compose/crypto/ui/components/chartintervals/ChartIntervalsButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/components/chartintervals/TimeIntervals.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/components/linechart/CoinPriceChart.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/components/linechart/CoinPriceLabelDrawer.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/components/linechart/ILabelDrawer.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Color.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Dimension.kt
  build.gradle.kts
  buildSrc/src/main/java/Versions.kt
Labels: type : feature

#48 [#20][Integrate] As a user, I can see the chart of coin prices
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailViewModel.kt
  app/src/test/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailViewModelTest.kt
Labels: type : feature

#58 Release - 0.5.0
  app/build.gradle.kts
  app/src/main/java/co/nimblehq/compose/crypto/ui/components/chartintervals/ChartIntervalsButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/components/chartintervals/TimeIntervals.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/components/linechart/CoinPriceChart.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/components/linechart/CoinPriceLabelDrawer.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/components/linechart/ILabelDrawer.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailViewModel.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Color.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Dimension.kt
  app/src/test/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailViewModelTest.kt
  build.gradle.kts
  buildSrc/src/main/java/Versions.kt
Labels: type : release

#59 [Chore] Bump version to 0.6.0
  buildSrc/src/main/java/Versions.kt
Labels: type : chore

#61 [#60] Fix: The Coin prices period text color show incorrect on Light mode
  app/src/main/java/co/nimblehq/compose/crypto/ui/components/chartintervals/ChartIntervalsButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Color.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Style.kt
Labels: type : bug
