Repository nimblehq/jetpack-compose-crypto, pull requests merged in 2022-11, with the labels that each got.

#56 [#22] [UI] As a user, I can see the shadow effect of the Profit card
  app/src/main/java/co/nimblehq/compose/crypto/extension/ModifierExt.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Dimension.kt
Labels: type : feature

#57 [#50] [Integrate] As a user, I can scroll down to refresh the data on Home screen
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeViewModel.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Style.kt
  buildSrc/src/main/java/Versions.kt
Labels: type : feature

#62 [#32] [Integrate] As a user, I can see more coins on the Trending list when scrolling down
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/LoadingState.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/preview/HomeScreenPreviewParameterProvider.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeViewModel.kt
Labels: type : feature

#63 Release - 0.6.0
  app/src/main/java/co/nimblehq/compose/crypto/extension/ModifierExt.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/LoadingState.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/components/chartintervals/ChartIntervalsButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/preview/HomeScreenPreviewParameterProvider.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeViewModel.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Color.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Dimension.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Style.kt
  buildSrc/src/main/java/Versions.kt
Labels: type : release

#64 [Chore] Bump version to 0.7.0
  buildSrc/src/main/java/Versions.kt
Labels: type : chore

#66 [Chore] Refactor Compose resources -> colors
  app/src/main/java/co/nimblehq/compose/crypto/ui/common/price/PriceChange.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/common/price/PriceChangeButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/components/chartintervals/ChartIntervalsButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/components/linechart/CoinPriceLabelDrawer.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/Appbar.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/SellBuyButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/SellBuyGroup.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/CoinItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/PortfolioCard.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/SeeAll.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/TrendingItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/AppColors.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Color.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Style.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Theme.kt
  detekt-config.yml
Labels: type : chore

#67 [Chore] Refactor Compose resources -> dimensions
  app/src/main/java/co/nimblehq/compose/crypto/extension/ModifierExt.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/common/price/PriceChange.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/common/price/PriceChangeButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/components/chartintervals/ChartIntervalsButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/SellBuyButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/SellBuyGroup.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/CoinItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/PortfolioCard.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/SeeAll.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/TrendingItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/AppDimensions.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Dimension.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Shape.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Style.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/TextDimension.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Theme.kt
Labels: type : chore

#68 [Chore] Refactor Compose resources -> styles
  app/src/main/java/co/nimblehq/compose/crypto/ui/common/price/PriceChange.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/common/price/PriceChangeButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/components/chartintervals/ChartIntervalsButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/Appbar.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/SellBuyButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/CoinItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/PortfolioCard.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/SeeAll.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/TrendingItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/AppStyles.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Shape.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Style.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Theme.kt
Labels: type : chore
