Repository nimblehq/jetpack-compose-crypto, pull requests merged in 2022-09, with the labels that each got.

#29 [Chore] Bump version to 0.2.0
  buildSrc/src/main/java/Versions.kt
Labels: type : chore

#25 [#16][Backend] As a user, I can see the chart of coin prices
  data/src/main/java/co/nimblehq/compose/crypto/data/model/response/CoinPriceResponse.kt
  data/src/main/java/co/nimblehq/compose/crypto/data/repository/CoinRepositoryImpl.kt
  data/src/main/java/co/nimblehq/compose/crypto/data/service/ApiService.kt
  domain/src/main/java/co/nimblehq/compose/crypto/domain/model/CoinPrice.kt
  domain/src/main/java/co/nimblehq/compose/crypto/domain/repository/CoinRepository.kt
  domain/src/main/java/co/nimblehq/compose/crypto/domain/usecase/GetCoinPricesUseCase.kt
Labels: type : feature

#27 [#7] [Integrate] As a user, I can see My Coins list on Home page
  .github/workflows/deploy_to_firebase_app_distribution.yml
  .github/workflows/review_pull_request.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/nimblehq/compose/crypto/CryptoComposeApplication.kt
  app/src/main/java/co/nimblehq/compose/crypto/extension/BigDecimalExt.kt
  app/src/main/java/co/nimblehq/compose/crypto/extension/DoubleExt.kt
  app/src/main/java/co/nimblehq/compose/crypto/extension/ViewModelExt.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/BaseActivity.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/BaseComposeFragment.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/BaseComposeFragmentCallbacks.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/BaseFragment.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/BaseFragmentCallbacks.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/BaseNavigator.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/base/BaseViewModel.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/MainViewModel.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/CoinItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeViewModel.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/PriceChange.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/TrendingItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/uimodel/CoinItemUiModel.kt
  app/src/main/res/drawable/ic_btc_bitcoin.png
  app/src/test/java/co/nimblehq/compose/crypto/test/CoroutineTestRule.kt
  app/src/test/java/co/nimblehq/compose/crypto/test/MockUtil.kt
  app/src/test/java/co/nimblehq/compose/crypto/test/ViewModelExt.kt
  app/src/test/java/co/nimblehq/compose/crypto/ui/screens/BaseViewModelTest.kt
  app/src/test/java/co/nimblehq/compose/crypto/ui/screens/home/HomeViewModelTest.kt
  buildSrc/src/main/java/Versions.kt
  data/build.gradle.kts
  data/src/main/java/co/nimblehq/compose/crypto/data/model/response/CoinItemResponse.kt
  data/src/main/java/co/nimblehq/compose/crypto/data/service/providers/BigDecimalAdapter.kt
  data/src/main/java/co/nimblehq/compose/crypto/data/service/providers/MoshiBuilderProvider.kt
  domain/src/main/java/co/nimblehq/compose/crypto/domain/model/CoinItem.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: type : feature

#31 [#14] [Integrate] As a user, I can see Trending list on Home page
  app/build.gradle.kts
  app/src/main/java/co/nimblehq/compose/crypto/ui/ErrorMapping.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/preview/CoinItemPreviewParameterProvider.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/preview/HomeScreenPreviewParameterProvider.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/CoinItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeViewModel.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/PriceChange.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/TrendingItem.kt
  app/src/test/java/co/nimblehq/compose/crypto/test/MockUtil.kt
  app/src/test/java/co/nimblehq/compose/crypto/ui/screens/home/HomeViewModelTest.kt
  data/src/main/java/co/nimblehq/compose/crypto/data/model/response/ErrorResponse.kt
Labels: type : feature

#35 [Chore] Update app launcher icon
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
Labels: type : chore

#37 Release - 0.2.0
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
Labels: type : release

#39 [Chore] Bump version to 0.3.0
  buildSrc/src/main/java/Versions.kt
Labels: type : chore

#28 [#17] Implement UI coin info on detail screen
  app/build.gradle.kts
  app/src/main/java/co/nimblehq/compose/crypto/extension/ViewModelExt.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/common/price/PriceChange.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/common/price/PriceChangeButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/MainActivity.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/Appbar.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/SellBuyButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/SellBuyGroup.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/CoinItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeViewModel.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/PortfolioCard.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/TrendingItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/navigation/CryptoNavGraph.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/navigation/CryptoScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Color.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Dimension.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Style.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/TextDimension.kt
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_heart.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/Versions.kt
  data/src/main/java/co/nimblehq/compose/crypto/data/model/response/CoinItemResponse.kt
Labels: type : feature

#40 [#34] [Chore] Update Detekt rules for Jetpack Compose
  app/src/main/java/co/nimblehq/compose/crypto/ui/common/price/PriceChange.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/common/price/PriceChangeButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/Appbar.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/SellBuyButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/SellBuyGroup.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/CoinItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeViewModel.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/PortfolioCard.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/SeeAll.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/TrendingItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/navigation/CryptoNavGraph.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Color.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Dimension.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/TextDimension.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Theme.kt
  data/src/main/java/co/nimblehq/compose/crypto/data/extension/NumberExt.kt
  data/src/main/java/co/nimblehq/compose/crypto/data/model/response/CoinItemResponse.kt
  detekt-config.yml
Labels: type : chore

#41 [#33] As a user, I can see the coin image fit circular and crop in center
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/CoinItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/TrendingItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Dimension.kt
Labels: type : chore

#43 [#15] [Backend] As a user, I can see coin information on Detail page
  data/src/main/java/co/nimblehq/compose/crypto/data/model/response/CoinDetailResponse.kt
  data/src/main/java/co/nimblehq/compose/crypto/data/model/response/CoinItemResponse.kt
  data/src/main/java/co/nimblehq/compose/crypto/data/model/response/CoinPriceResponse.kt
  data/src/main/java/co/nimblehq/compose/crypto/data/repository/CoinRepositoryImpl.kt
  data/src/main/java/co/nimblehq/compose/crypto/data/service/ApiService.kt
  domain/src/main/java/co/nimblehq/compose/crypto/domain/model/CoinDetail.kt
  domain/src/main/java/co/nimblehq/compose/crypto/domain/repository/CoinRepository.kt
  domain/src/main/java/co/nimblehq/compose/crypto/domain/usecase/GetCoinDetailUseCase.kt
Labels: type : feature

#46 Release - 0.3.0
  app/build.gradle.kts
  app/src/main/java/co/nimblehq/compose/crypto/extension/ViewModelExt.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/common/price/PriceChange.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/common/price/PriceChangeButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/MainActivity.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/Appbar.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/SellBuyButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/SellBuyGroup.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/CoinItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeViewModel.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/PortfolioCard.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/SeeAll.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/TrendingItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/navigation/CryptoNavGraph.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/navigation/CryptoScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Color.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Dimension.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Style.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/TextDimension.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/theme/Theme.kt
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_heart.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/Versions.kt
  data/src/main/java/co/nimblehq/compose/crypto/data/extension/NumberExt.kt
  data/src/main/java/co/nimblehq/compose/crypto/data/model/response/CoinDetailResponse.kt
  data/src/main/java/co/nimblehq/compose/crypto/data/model/response/CoinItemResponse.kt
  data/src/main/java/co/nimblehq/compose/crypto/data/model/response/CoinPriceResponse.kt
  data/src/main/java/co/nimblehq/compose/crypto/data/repository/CoinRepositoryImpl.kt
  data/src/main/java/co/nimblehq/compose/crypto/data/service/ApiService.kt
  detekt-config.yml
  domain/src/main/java/co/nimblehq/compose/crypto/domain/model/CoinDetail.kt
  domain/src/main/java/co/nimblehq/compose/crypto/domain/repository/CoinRepository.kt
  domain/src/main/java/co/nimblehq/compose/crypto/domain/usecase/GetCoinDetailUseCase.kt
Labels: type : release

#47 [Chore] Bump version to 0.4.0
  buildSrc/src/main/java/Versions.kt
Labels: type : chore

#45 [#19] Integrate coin info detail
  app/src/main/java/co/nimblehq/compose/crypto/ui/common/price/PriceChangeButton.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/preview/DetailScreenPreviewParameterProvider.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/Appbar.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailViewModel.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/CoinItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeScreen.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeViewModel.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/PortfolioCard.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/TrendingItem.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/screens/navigation/CryptoNavGraph.kt
  app/src/main/java/co/nimblehq/compose/crypto/ui/uimodel/CoinDetailUiModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/co/nimblehq/compose/crypto/test/MockUtil.kt
  app/src/test/java/co/nimblehq/compose/crypto/ui/screens/detail/DetailViewModelTest.kt
Labels: type : feature
